on:
  push:
  pull_request:
    branches: [ master ]

env:
  # This is the java version that will trigger an upload to the SNAPSHOT maven store
  # Other Java versions within the matrix are just unit tested
  MAIN_JAVA_VERSION: 1.8
  # We will only publish the build artifacts to our pseudo snapshot repo for a push on
  # this branch
  PUBLISH_BRANCH: refs/heads/master

jobs:
  build:
    strategy:
      matrix:
        java-version: [1.8]

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --tags --unshallow

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Setup GPG secrets
      run: |
        gpg --version
        cat <(echo "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | base64 -d | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG

    - run: ./millw -i show pluginVersion

    - name: Publish to Maven Central
      if: ${{ matrix.java-version == env.MAIN_JAVA_VERSION && github.ref == env.PUBLISH_BRANCH && github.event_name == 'push' }}
      run: ./millw blended.mill.publish --sonatypeCreds "${{ secrets.OSSRH_USER}}:${{ secrets.OSSRH_PASSWORD }}" --gpgArgs "--passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}},--batch,--yes,-a,-b,--pinentry-mode,loopback" --readTimeout 600000 --release true --signed true
